apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: N8N_HOST
          value: "aiwork-contabo.tawfiqulbari.work"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_EDITOR_BASE_URL
          value: "https://aiwork-contabo.tawfiqulbari.work"
        - name: N8N_USER_MANAGEMENT_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: jwt-secret
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: encryption-key
        - name: N8N_OAUTH_GOOGLE_CLIENT_ID
          value: "your-google-oauth-client-id"
        - name: N8N_OAUTH_GOOGLE_CLIENT_SECRET
          value: "your-google-oauth-client-secret"
        - name: N8N_OAUTH_GOOGLE_CALLBACK_URL
          value: "https://aiwork-contabo.tawfiqulbari.work/rest/oauth2-credential/callback"
        - name: N8N_USER_MANAGEMENT_DISABLED
          value: "false"
        - name: N8N_USER_MANAGEMENT_JWT_DURATION
          value: "7d"
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-pvc