apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  jwt-secret: your-super-secure-jwt-secret-here-change-this-in-production
  encryption-key: your-32-character-encryption-key-here-change
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-google-oauth
  namespace: n8n
type: Opaque
stringData:
  client-id: your-google-oauth-client-id
  client-secret: your-google-oauth-client-secret